/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type { } from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  jsonb,
  timestamp,
  numeric,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";

export const services_featureList = pgTable(
  "services_featureList",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    feature: varchar("feature").notNull(),
  },
  (columns) => [
    index("services_featureList_order_idx").on(columns._order),
    index("services_featureList_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_featureList_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services_benefit_list = pgTable(
  "services_benefit_list",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    benefit: varchar("benefit").notNull(),
  },
  (columns) => [
    index("services_benefit_list_order_idx").on(columns._order),
    index("services_benefit_list_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_benefit_list_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services_process_list = pgTable(
  "services_process_list",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    stepTitle: varchar("step_title").notNull(),
    stepDescription: varchar("step_description").notNull(),
  },
  (columns) => [
    index("services_process_list_order_idx").on(columns._order),
    index("services_process_list_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_process_list_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services_imageGallery = pgTable(
  "services_imageGallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
  },
  (columns) => [
    index("services_imageGallery_order_idx").on(columns._order),
    index("services_imageGallery_parent_id_idx").on(columns._parentID),
    index("services_imageGallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [services.id],
      name: "services_imageGallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const services = pgTable(
  "services",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    subtitle: varchar("subtitle").notNull(),
    icon: integer("icon_id").references(() => media.id, {
      onDelete: "set null",
    }),
    description: varchar("description").notNull(),
    detailedDescription: jsonb("detailed_description").notNull(),
    pricing: varchar("pricing").notNull(),
    timeline: varchar("timeline").notNull(),
    bannerImage: integer("bannerImage_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("services_icon_idx").on(columns.icon),
    index("services_bannerImage_idx").on(columns.bannerImage),
    index("services_updated_at_idx").on(columns.updatedAt),
    index("services_created_at_idx").on(columns.createdAt),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_tablet_url: varchar("sizes_tablet_url"),
    sizes_tablet_width: numeric("sizes_tablet_width", { mode: "number" }),
    sizes_tablet_height: numeric("sizes_tablet_height", { mode: "number" }),
    sizes_tablet_mimeType: varchar("sizes_tablet_mime_type"),
    sizes_tablet_filesize: numeric("sizes_tablet_filesize", { mode: "number" }),
    sizes_tablet_filename: varchar("sizes_tablet_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_tablet_sizes_tablet_filename_idx").on(
      columns.sizes_tablet_filename,
    ),
  ],
);

export const tags = pgTable(
  "tags",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("tags_title_idx").on(columns.title),
    index("tags_updated_at_idx").on(columns.updatedAt),
    index("tags_created_at_idx").on(columns.createdAt),
  ],
);

export const portfolio_projects_featureList = pgTable(
  "portfolio_projects_featureList",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    feature: varchar("feature").notNull(),
  },
  (columns) => [
    index("portfolio_projects_featureList_order_idx").on(columns._order),
    index("portfolio_projects_featureList_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [portfolio_projects.id],
      name: "portfolio_projects_featureList_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const portfolio_projects_imageGallery = pgTable(
  "portfolio_projects_imageGallery",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    caption: varchar("caption").notNull(),
  },
  (columns) => [
    index("portfolio_projects_imageGallery_order_idx").on(columns._order),
    index("portfolio_projects_imageGallery_parent_id_idx").on(
      columns._parentID,
    ),
    index("portfolio_projects_imageGallery_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [portfolio_projects.id],
      name: "portfolio_projects_imageGallery_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const portfolio_projects = pgTable(
  "portfolio_projects",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    subtitle: varchar("subtitle").notNull(),
    client: varchar("client").notNull(),
    location: varchar("location").notNull(),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    description: varchar("description").notNull(),
    detailed_description: jsonb("detailed_description").notNull(),
    challenge: varchar("challenge").notNull(),
    solution: varchar("solution").notNull(),
    bannerImage: integer("bannerImage_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("portfolio_projects_bannerImage_idx").on(columns.bannerImage),
    index("portfolio_projects_updated_at_idx").on(columns.updatedAt),
    index("portfolio_projects_created_at_idx").on(columns.createdAt),
  ],
);

export const portfolio_projects_rels = pgTable(
  "portfolio_projects_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    tagsID: integer("tags_id"),
  },
  (columns) => [
    index("portfolio_projects_rels_order_idx").on(columns.order),
    index("portfolio_projects_rels_parent_idx").on(columns.parent),
    index("portfolio_projects_rels_path_idx").on(columns.path),
    index("portfolio_projects_rels_tags_id_idx").on(columns.tagsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [portfolio_projects.id],
      name: "portfolio_projects_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "portfolio_projects_rels_tags_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    servicesID: integer("services_id"),
    mediaID: integer("media_id"),
    tagsID: integer("tags_id"),
    "portfolio-projectsID": integer("portfolio_projects_id"),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_services_id_idx").on(
      columns.servicesID,
    ),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_tags_id_idx").on(columns.tagsID),
    index("payload_locked_documents_rels_portfolio_projects_id_idx").on(
      columns["portfolio-projectsID"],
    ),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["servicesID"]],
      foreignColumns: [services.id],
      name: "payload_locked_documents_rels_services_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tagsID"]],
      foreignColumns: [tags.id],
      name: "payload_locked_documents_rels_tags_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["portfolio-projectsID"]],
      foreignColumns: [portfolio_projects.id],
      name: "payload_locked_documents_rels_portfolio_projects_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_services_featureList = relations(
  services_featureList,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_featureList._parentID],
      references: [services.id],
      relationName: "featureList",
    }),
  }),
);
export const relations_services_benefit_list = relations(
  services_benefit_list,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_benefit_list._parentID],
      references: [services.id],
      relationName: "benefitList",
    }),
  }),
);
export const relations_services_process_list = relations(
  services_process_list,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_process_list._parentID],
      references: [services.id],
      relationName: "processList",
    }),
  }),
);
export const relations_services_imageGallery = relations(
  services_imageGallery,
  ({ one }) => ({
    _parentID: one(services, {
      fields: [services_imageGallery._parentID],
      references: [services.id],
      relationName: "imageGallery",
    }),
    image: one(media, {
      fields: [services_imageGallery.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_services = relations(services, ({ one, many }) => ({
  icon: one(media, {
    fields: [services.icon],
    references: [media.id],
    relationName: "icon",
  }),
  featureList: many(services_featureList, {
    relationName: "featureList",
  }),
  benefitList: many(services_benefit_list, {
    relationName: "benefitList",
  }),
  processList: many(services_process_list, {
    relationName: "processList",
  }),
  bannerImage: one(media, {
    fields: [services.bannerImage],
    references: [media.id],
    relationName: "bannerImage",
  }),
  imageGallery: many(services_imageGallery, {
    relationName: "imageGallery",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_tags = relations(tags, () => ({}));
export const relations_portfolio_projects_featureList = relations(
  portfolio_projects_featureList,
  ({ one }) => ({
    _parentID: one(portfolio_projects, {
      fields: [portfolio_projects_featureList._parentID],
      references: [portfolio_projects.id],
      relationName: "featureList",
    }),
  }),
);
export const relations_portfolio_projects_imageGallery = relations(
  portfolio_projects_imageGallery,
  ({ one }) => ({
    _parentID: one(portfolio_projects, {
      fields: [portfolio_projects_imageGallery._parentID],
      references: [portfolio_projects.id],
      relationName: "imageGallery",
    }),
    image: one(media, {
      fields: [portfolio_projects_imageGallery.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_portfolio_projects_rels = relations(
  portfolio_projects_rels,
  ({ one }) => ({
    parent: one(portfolio_projects, {
      fields: [portfolio_projects_rels.parent],
      references: [portfolio_projects.id],
      relationName: "_rels",
    }),
    tagsID: one(tags, {
      fields: [portfolio_projects_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
  }),
);
export const relations_portfolio_projects = relations(
  portfolio_projects,
  ({ one, many }) => ({
    featureList: many(portfolio_projects_featureList, {
      relationName: "featureList",
    }),
    bannerImage: one(media, {
      fields: [portfolio_projects.bannerImage],
      references: [media.id],
      relationName: "bannerImage",
    }),
    imageGallery: many(portfolio_projects_imageGallery, {
      relationName: "imageGallery",
    }),
    _rels: many(portfolio_projects_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: "services",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    tagsID: one(tags, {
      fields: [payload_locked_documents_rels.tagsID],
      references: [tags.id],
      relationName: "tags",
    }),
    "portfolio-projectsID": one(portfolio_projects, {
      fields: [payload_locked_documents_rels["portfolio-projectsID"]],
      references: [portfolio_projects.id],
      relationName: "portfolio-projects",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  services_featureList: typeof services_featureList;
  services_benefit_list: typeof services_benefit_list;
  services_process_list: typeof services_process_list;
  services_imageGallery: typeof services_imageGallery;
  services: typeof services;
  media: typeof media;
  tags: typeof tags;
  portfolio_projects_featureList: typeof portfolio_projects_featureList;
  portfolio_projects_imageGallery: typeof portfolio_projects_imageGallery;
  portfolio_projects: typeof portfolio_projects;
  portfolio_projects_rels: typeof portfolio_projects_rels;
  payload_kv: typeof payload_kv;
  users_sessions: typeof users_sessions;
  users: typeof users;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_services_featureList: typeof relations_services_featureList;
  relations_services_benefit_list: typeof relations_services_benefit_list;
  relations_services_process_list: typeof relations_services_process_list;
  relations_services_imageGallery: typeof relations_services_imageGallery;
  relations_services: typeof relations_services;
  relations_media: typeof relations_media;
  relations_tags: typeof relations_tags;
  relations_portfolio_projects_featureList: typeof relations_portfolio_projects_featureList;
  relations_portfolio_projects_imageGallery: typeof relations_portfolio_projects_imageGallery;
  relations_portfolio_projects_rels: typeof relations_portfolio_projects_rels;
  relations_portfolio_projects: typeof relations_portfolio_projects;
  relations_payload_kv: typeof relations_payload_kv;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
